Add gate:precondition:check which checks for presence of certain required environment variables from precondition stage (like those set in set:version)

diff --git a/core/setup.yml b/core/setup.yml
--- a/core/setup.yml
+++ b/core/setup.yml
@@ -3,6 +3,7 @@ include:
   - local: core/.rules.yml
   - local: core/.gate_base.yml
   - local: core/.base.yml
+  - local: core/.set_version.yml
 
 pull:setup:artifacts:
   script:
@@ -18,6 +19,46 @@ pull:setup:artifacts:
       - .config/*
       - semver.py
       - release.sh
+
+gate:precondition:check:
+  stage: prebuild
+  extends:
+    - .rp_base
+  script: | 
+    #!/usr/bin/env bash
+    set -e
+    
+    fail_job=0
+    
+    echo "⭐  Checking for required environment variables  ⭐ "
+    required_envars=( TAG DESCRIPTION APP VERSION BUILD RELEASE_SEMVER )
+    for var in "${required_envars[@]}"
+    do
+      value=$(eval echo \${"$var"})
+      if [[ -z $value ]]; then
+        echo "   ⛔  ${var}"
+        fail_job=1
+      else
+        echo "   ✅  ${var}=${value}"
+      fi
+    done
+    
+    echo "💫  Checking for recommended environment variables  💫 "
+    recommended_envars=( VERSION_PATCH VERSION_MINOR VERSION_MAJOR VERSION_CODE CURRENT_VERSION )
+    for var in "${recommended_envars[@]}"
+    do
+      value=$(eval echo \${"$var"})
+      if [[ -z $value ]]; then
+        echo "   ⚠️  ${var}"
+      else
+        echo "   ✅  ${var}=${value}"
+      fi
+    done
+    
+    if [[ $fail_job != 0 ]]; then
+      echo "One or more ⭐ required⭐  ENVARs are unset, failing job"
+    fi
+    exit $fail_job
 
 set:stable:tag:
   extends:
@@ -50,3 +91,7 @@ set:stable:tag:
     - job: 'publish:candidate'
       optional: true
     - job: 'set:version'
+
+set:version:
+  extends:
+   - .set:version
